Repository aesara-devs/aesara, pull requests merged in 2020-12, with the labels that each got.

#206 Fix mkl warning in default_blas_ldflags
  tests/test_config.py
  theano/configdefaults.py
Labels: bug

#194 Update print warnings to use warnings.warn
  tests/gof/test_utils.py
  tests/tensor/test_basic.py
  tests/tensor/test_blas_c.py
  theano/compile/debugmode.py
  theano/compile/mode.py
  theano/gof/cmodule.py
  theano/gof/link.py
  theano/gof/toolbox.py
  theano/gof/utils.py
  theano/gpuarray/__init__.py
  theano/gradient.py
  theano/sandbox/blocksparse.py
  theano/sandbox/conv.py
  theano/sandbox/softsign.py
  theano/scan/basic.py
  theano/scan/opt.py
  theano/scan/utils.py
  theano/sparse/__init__.py
  theano/sparse/basic.py
  theano/tensor/basic.py
  theano/tensor/nnet/conv.py
  theano/tensor/nnet/nnet.py
  theano/tensor/opt.py
  theano/tensor/raw_random.py
  theano/tensor/signal/pool.py
  theano/tensor/type.py
Labels: enhancement

#212 Fix JAX list index error in Scan conversion
  theano/sandbox/jaxify.py
Labels: bug, jax

#213 Fix CI failure due to missing coverage when tests are skipped
  .github/workflows/test.yml
Labels: bug, ci

#214 Get rid of singleton design and most module-level variables
  .github/workflows/test.yml
  tests/compile/test_builders.py
  tests/compile/test_debugmode.py
  tests/compile/test_ops.py
  tests/gof/test_compute_test_value.py
  tests/gof/test_destroyhandler.py
  tests/gof/test_fg.py
  tests/gof/test_op.py
  tests/gof/test_opt.py
  tests/gof/test_types.py
  tests/gpuarray/test_opt.py
  tests/gpuarray/test_rng_mrg.py
  tests/gpuarray/test_subtensor.py
  tests/sandbox/test_jax.py
  tests/sandbox/test_rng_mrg.py
  tests/scalar/test_type.py
  tests/scan/test_basic.py
  tests/tensor/_test_mpi_roundtrip.py
  tests/tensor/nnet/test_abstract_conv.py
  tests/tensor/nnet/test_neighbours.py
  tests/tensor/nnet/test_nnet.py
  tests/tensor/test_basic.py
  tests/tensor/test_blas.py
  tests/tensor/test_blas_c.py
  tests/tensor/test_extra_ops.py
  tests/tensor/test_mpi.py
  tests/tensor/test_nlinalg.py
  tests/tensor/test_opt.py
  tests/tensor/test_subtensor.py
  tests/tensor/test_type.py
  tests/tensor/utils.py
  tests/test_config.py
  tests/test_gradient.py
  theano/__init__.py
  theano/compile/builders.py
  theano/compile/debugmode.py
  theano/compile/function/types.py
  theano/configdefaults.py
  theano/configparser.py
  theano/gof/cc.py
  theano/gof/type.py
  theano/gof/vm.py
  theano/sandbox/rng_mrg.py
  theano/scalar/basic.py
  theano/tensor/basic.py
  theano/tensor/elemwise.py
  theano/tensor/nnet/bn.py
  theano/tensor/subtensor.py
  theano/utils.py
Labels: refactor

#137 Add new RandomVariable Op and optimizations
  doc/library/scan.txt
  doc/library/tensor/index.txt
  doc/library/tensor/random/basic.txt
  doc/library/tensor/random/utils.txt
  doc/library/tensor/raw_random.txt
  doc/nextml2015/presentation.tex
  doc/tutorial/examples.txt
  doc/tutorial/loop.txt
  requirements.txt
  tests/compile/test_builders.py
  tests/gof/test_graph.py
  tests/gpuarray/test_multinomial.py
  tests/gpuarray/test_rng_mrg.py
  tests/gpuarray/test_scan.py
  tests/misc/test_pkl_utils.py
  tests/sandbox/test_jax.py
  tests/sandbox/test_multinomial_wo_replacement.py
  tests/sandbox/test_rng_mrg.py
  tests/scan/test_basic.py
  tests/tensor/random/__init__.py
  tests/tensor/random/test_basic.py
  tests/tensor/random/test_op.py
  tests/tensor/random/test_opt.py
  tests/tensor/random/test_type.py
  tests/tensor/random/test_utils.py
  tests/tensor/random/test_var.py
  tests/tensor/test_basic.py
  tests/tensor/test_raw_random.py
  tests/tensor/test_shared_randomstreams.py
  tests/test_gradient.py
  theano/__init__.py
  theano/compile/profiling.py
  theano/gof/graph.py
  theano/gpuarray/rng_mrg.py
  theano/sandbox/rng_mrg.py
  theano/tensor/__init__.py
  theano/tensor/basic.py
  theano/tensor/random/__init__.py
  theano/tensor/random/basic.py
  theano/tensor/random/op.py
  theano/tensor/random/opt.py
  theano/tensor/random/type.py
  theano/tensor/random/utils.py
  theano/tensor/random/var.py
  theano/tensor/raw_random.py
  theano/tensor/shared_randomstreams.py
Labels: important, new operator

#219 Move JAX linker to new "link" module
  tests/link/test_jax.py
  theano/compile/mode.py
  theano/link/__init__.py
  theano/link/jax/__init__.py
  theano/link/jax/jax_dispatch.py
  theano/link/jax/jax_linker.py
Labels: refactor

#221 Clean config importing
  tests/gof/test_cmodule.py
  tests/gof/test_compiledir.py
  tests/tensor/test_mpi.py
  tests/test_config.py
  theano/__init__.py
  theano/configdefaults.py
  theano/configparser.py
  theano/gof/cmodule.py
  theano/misc/elemwise_openmp_speedup.py
  theano/misc/windows.py
  theano/scan/__init__.py
  theano/utils.py
Labels: refactor

#228 Move linkers to link module
  bin/theano_cache.py
  doc/extending/pipeline.txt
  doc/sandbox/debugging_with_stepmode.txt
  tests/compile/test_modes.py
  tests/gof/test_lazy.py
  tests/gpuarray/test_elemwise.py
  tests/link/test_cc.py
  tests/link/test_cmodule.py
  tests/link/test_link.py
  tests/link/test_vm.py
  tests/record.py
  tests/scalar/test_basic.py
  tests/scalar/test_basic_sympy.py
  tests/tensor/nnet/test_conv.py
  tests/tensor/random/test_type.py
  tests/tensor/test_basic.py
  tests/tensor/test_elemwise.py
  tests/tensor/test_opt_uncanonicalize.py
  tests/test_ifelse.py
  theano/__init__.py
  theano/compile/debugmode.py
  theano/compile/function/types.py
  theano/compile/io.py
  theano/compile/mode.py
  theano/compile/monitormode.py
  theano/compile/nanguardmode.py
  theano/compile/sharedvalue.py
  theano/gof/__init__.py
  theano/gof/link.py
  theano/gof/op.py
  theano/gpuarray/basic_ops.py
  theano/gpuarray/dnn.py
  theano/gpuarray/opt.py
  theano/link/__init__.py
  theano/link/basic.py
  theano/link/c/__init__.py
  theano/link/c/basic.py
  theano/link/c/c_code/lazylinker_c.c
  theano/link/c/c_code/theano_mod_helper.h
  theano/link/c/cmodule.py
  theano/link/c/cutils.py
  theano/link/c/cvm.py
  theano/link/c/exceptions.py
  theano/link/c/lazylinker_c.py
  theano/link/jax/jax_linker.py
  theano/link/utils.py
  theano/link/vm.py
  theano/scan/op.py
  theano/scan/scan_perform.pyx
  theano/scan/scan_perform_ext.py
  theano/tensor/blas_c.py
  theano/tensor/blas_headers.py
  theano/tensor/elemwise.py
  theano/tensor/nnet/conv.py
  theano/tensor/nnet/ctc.py
  theano/tensor/random/op.py
  theano/utils.py
Labels: refactor

#251 Fix typo in normal RandomVariable's default arguments
  theano/tensor/random/basic.py
Labels: bug, important
