Repository aesara-devs/aesara, pull requests merged in 2020-11, with the labels that each got.

#145 Create a BroadcastTo Op for NumPy's broadcast_to function
  tests/tensor/test_extra_ops.py
  theano/tensor/extra_ops.py
Labels: enhancement, new operator

#157 Add handling for non-NumPy types in Shape/Shape_i
  tests/compile/test_ops.py
  tests/tensor/test_basic.py
  theano/compile/ops.py
Labels: enhancement

#161 Avoid Elemwise fusion for scalar Ops without C implementations
  tests/tensor/test_opt.py
  theano/tensor/opt.py
Labels: bug, optimizations

#166 Return the correct output for multi-output inputs in a JAXified graph
  tests/sandbox/test_jax.py
  theano/sandbox/jaxify.py
Labels: bug, jax

#168 Update Cython-generated Scan code
  theano/scan/c_code/scan_perform.c
  theano/scan/numpy_api_changes.diff
  theano/scan/scan_perform.pyx
  theano/scan/scan_perform_ext.py
Labels: enhancement, important

#167 Refactor setup.py
  setup.py
Labels: enhancement, important, refactor

#174 Update conda CI steps
  .github/workflows/test.yml
Labels: bug, ci, important

#173 Use isinstance to check types in filter method
  tests/scalar/test_basic.py
  tests/scalar/test_type.py
  tests/tensor/test_type.py
  tests/tensor/utils.py
  theano/gof/opt.py
  theano/ifelse.py
  theano/misc/pkl_utils.py
  theano/scalar/basic.py
  theano/scan/opt.py
  theano/tensor/opt.py
  theano/tensor/type.py
  theano/tensor/var.py
Labels: bug, enhancement

#176 Update function graph interface
  tests/gof/test_fg.py
  tests/gof/test_opt.py
  tests/gof/utils.py
  theano/gof/fg.py
Labels: enhancement, optimizations

#169 Add ScanOp jaxification
  tests/sandbox/test_jax.py
  theano/sandbox/jaxify.py
  theano/scan/utils.py
Labels: important, jax

#193 Rename ReplacementDidntRemovedError to ReplacementDidNotRemoveError
  theano/gof/__init__.py
  theano/gof/toolbox.py
  theano/tensor/blas.py
Labels: refactor

#196 Refactor tests.tensor.nnet optimization tests
  tests/tensor/nnet/test_nnet.py
Labels: refactor

#199 Fix JAX conversion for AdvancedIncSubtensor1
  tests/sandbox/test_jax.py
  theano/sandbox/jaxify.py
Labels: bug, jax

#191 Reconfigure codecov to reduce false alarm rate.
  .github/workflows/test.yml
  codecov.yml
Labels: ci
