Repository aesara-devs/aesara, pull requests merged in 2020-10, with the labels that each got.

#75 Remove unnecessary self argument in super call
  theano/tensor/basic.py
Labels: bug

#76 Add a test for jaxification of a shared variable
  tests/sandbox/test_jax.py
Labels: enhancement, jax

#71 Replacing Travis with GitHub Actions
  .coveragerc
  .github/workflows/test.yml
  .travis.yml
Labels: important

#83 Prevent CI from running Python tests for non-Python changes
  .github/workflows/test.yml
Labels: ci, enhancement

#85 Stop importing test suite from __init__
  doc/tutorial/debug_faq.txt
  setup.cfg
  tests/gpuarray/test_basic_ops.py
  tests/gpuarray/test_gemmcorr.py
  tests/gpuarray/test_opt.py
  tests/gpuarray/test_type.py
  tests/test_breakpoint.py
  tests/unittest_tools.py
  theano/__init__.py
  theano/breakpoint.py
  theano/compile/debugmode.py
  theano/gpuarray/opt.py
  theano/sandbox/cuda/__init__.py
  theano/sparse/sandbox/truedot.py
Labels: testing

#82 Update README
  .circleci/config.yml
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .jenkins/gpuarray-branch
  .jenkins/jenkins_buildbot_mac.sh
  .jenkins/jenkins_buildbot_nogpp.sh
  .jenkins/jenkins_buildbot_python2.sh
  .jenkins/jenkins_buildbot_python2_32bit.sh
  .jenkins/jenkins_buildbot_python2_debug.sh
  .jenkins/jenkins_buildbot_python3.sh
  .jenkins/jenkins_buildbot_release_extra.sh
  .jenkins/jenkins_buildbot_windows.bat
  .jenkins/jenkins_pr_build_cache.sh
  .jenkins/jenkins_pr_core.sh
  .jenkins/jenkins_pr_gpu.sh
  .jenkins/jenkins_pr_mac.sh
  .jenkins/jenkins_pr_pretest.sh
  .jenkins/jenkins_pr_win.bat
  ISSUE_TEMPLATE.md
  README.rst
  Theano.pyproj
  Theano.sln
Labels: documentation, enhancement

#90 Make jax.numpy.unique tests involving non-concrete input expected fails
  tests/sandbox/test_jax.py
  theano/sandbox/jaxify.py
Labels: bug, jax

#78 Adding action to publish to PyPI
  .github/workflows/pypi.yml
Labels: ci, important

#102 Convert boolean indices to integers when determining broadcast pattern
  tests/tensor/test_subtensor.py
  theano/tensor/subtensor.py
Labels: bug, important

#104 Fix exception handling in as_tensor_variable
  tests/tensor/test_basic.py
  theano/scalar/basic.py
  theano/tensor/__init__.py
  theano/tensor/basic.py
  theano/tensor/var.py
Labels: bug, important

#108 Prevent test value computation from complaining about subtensor creation
  tests/tensor/test_subtensor.py
  theano/tensor/subtensor.py
Labels: bug, important

#110 Enforce sane test values
  doc/library/misc/pkl_utils.txt
  tests/gof/test_compute_test_value.py
  tests/gof/test_fg.py
  tests/gof/test_fg_old_crash.pkl
  tests/gof/test_op.py
  tests/gpuarray/test_multinomial.py
  tests/gpuarray/test_pickle.py
  tests/gpuarray/test_type.py
  tests/sandbox/test_multinomial.py
  tests/sandbox/test_multinomial_wo_replacement.py
  tests/unittest_tools.py
  theano/compile/debugmode.py
  theano/gof/cmodule.py
  theano/gof/compilelock.py
  theano/gof/graph.py
  theano/gof/op.py
  theano/gof/utils.py
  theano/gof/vm.py
  theano/misc/pkl_utils.py
  theano/printing.py
  theano/tensor/nnet/conv.py
  theano/tensor/opt.py
Labels: bug

#111 Add a pre-commit config
  .pre-commit-config.yaml
  requirements.txt
Labels: enhancement

#113 Update and add missing docstrings in theano.gof.op
  theano/gof/op.py
Labels: documentation

#114 Update and add missing docstrings in theano.gof.graph
  theano/gof/graph.py
Labels: documentation

#112 Move get_test_value method to the Variable (sub)classes
  tests/gof/test_op.py
  tests/tensor/test_basic.py
  theano/__init__.py
  theano/compile/sharedvalue.py
  theano/gof/__init__.py
  theano/gof/fg.py
  theano/gof/graph.py
  theano/gof/op.py
  theano/gof/utils.py
  theano/gradient.py
  theano/scan_module/scan.py
  theano/scan_module/scan_utils.py
  theano/tensor/blas.py
  theano/tensor/opt.py
Labels: enhancement, refactor

#117 Implementing exponentiation by squaring for matrix power
  tests/tensor/test_nlinalg.py
  theano/tensor/nlinalg.py
Labels: enhancement

#125 Split apart broadcast_shape so that it can work with many arguments
  theano/tensor/extra_ops.py
Labels: enhancement

#101 Refactor tests.tensor.test_basic
  .github/workflows/test.yml
  .gitignore
  doc/extending/unittest.txt
  setup.cfg
  tests/gpuarray/test_basic_ops.py
  tests/gpuarray/test_linalg.py
  tests/gpuarray/test_opt.py
  tests/scalar/test_basic.py
  tests/tensor/nnet/test_nnet.py
  tests/tensor/nnet/test_sigm.py
  tests/tensor/test_basic.py
  tests/tensor/test_basic_scipy.py
  tests/tensor/test_blas.py
  tests/tensor/test_inplace.py
  tests/tensor/test_subtensor.py
  tests/tensor/utils.py
  tests/typed_list/test_opt.py
  tests/typed_list/test_type.py
  theano/gradient.py
  theano/scalar/basic_scipy.py
Labels: refactor, testing

#124 [WIP] Change coverage to codecov
  .github/workflows/test.yml
  .gitignore
  codecov.yml
Labels: ci, testing

#136 Fix copy error in compute_test_value
  tests/gof/test_compute_test_value.py
  theano/gof/op.py
Labels: bug
