Repository aesara-devs/aesara, pull requests merged in 2021-04, with the labels that each got.

#358 xfail JAX tests after mandatory "omnistaging" update
  aesara/link/jax/jax_dispatch.py
  requirements.txt
  tests/link/test_jax.py
Labels: important, jax

#367 Make SpecifyShape work for scalar shapes too
  aesara/tensor/shape.py
  tests/tensor/test_shape.py
Labels: bug

#370 Add a dtype option to aesara.tensor.as_tensor_variable
  aesara/tensor/__init__.py
  aesara/tensor/basic.py
  tests/tensor/test_basic.py
Labels: enhancement

#364 Add local log - exp optimization
  aesara/tensor/math_opt.py
  tests/tensor/test_math_opt.py
Labels: optimizations

#374 Fix `nan` comparison in `Scalar.filter` and simplify `TensorType.values_eq`
  aesara/scalar/basic.py
  tests/scalar/test_type.py
Labels: bug

#380 Implement `*IncSubtensor*` translations for Numba
  aesara/link/numba/dispatch.py
  tests/link/test_numba.py
Labels: numba

#383 Add a `tests.link.test_utils` module
  tests/link/test_utils.py
Labels: important

#382 Allow `AdvancedIncSubtensor` to be in-placed
  aesara/tensor/basic_opt.py
  aesara/tensor/subtensor.py
  tests/tensor/test_basic_opt.py
  tests/tensor/test_subtensor.py
Labels: enhancement, important

#386 Update MultinomialRV docstring to match new broadcasting behavior
  aesara/tensor/random/basic.py
Labels: documentation
