Repository aesara-devs/aesara, pull requests merged in 2021-01, with the labels that each got.

#254 Preempt missing CVM and fall back to non-C VM in VMLinker.make_vm
  tests/link/test_vm.py
  theano/link/vm.py
Labels: bug, important

#265 Restrict mamba/conda updates to CPython
  .github/workflows/test.yml
Labels: bug, important

#266 Add gof OP documentation and surface to index
  doc/conf.py
  doc/library/gof/index.txt
  doc/library/gof/op.txt
Labels: documentation

#271 Use broadcasted output shape in local_useless_switch optimization
  tests/tensor/test_opt.py
  theano/tensor/opt.py
Labels: bug, important, optimizations

#278 Fix a bug involving thread local memory initialization
  tests/compile/test_compilelock.py
  theano/compile/compilelock.py
Labels: bug, important
