Repository aesara-devs/aesara, pull requests merged in 2021-09, with the labels that each got.

#473 Add optimizations to simplify unnecessary `logit` - `sigmoid` expressions
  aesara/tensor/math_opt.py
  tests/tensor/test_math_opt.py
Labels: enhancement, important, optimizations

#591 Split `aesara.link.numba.dispatch` into distinct modules
  aesara/link/numba/dispatch.py
  aesara/link/numba/dispatch/__init__.py
  aesara/link/numba/dispatch/basic.py
  aesara/link/numba/dispatch/elemwise.py
  aesara/link/numba/dispatch/extra_ops.py
  aesara/link/numba/dispatch/nlinalg.py
  aesara/link/numba/dispatch/random.py
  aesara/link/numba/dispatch/scalar.py
  aesara/link/numba/dispatch/tensor_basic.py
  aesara/link/numba/linker.py
  tests/link/test_numba.py
Labels: important, refactor, numba

#589 Remove MKL warning.
  aesara/link/c/cmodule.py
  tests/link/c/test_cmodule.py
Labels: C-backend
