Repository aesara-devs/aesara, pull requests merged in 2021-07, with the labels that each got.

#507 Work around SciPy squeeze defect
  aesara/tensor/random/basic.py
  aesara/tensor/random/op.py
  tests/tensor/random/test_basic.py
  tests/unittest_tools.py
Labels: bug, important, numpy compatibility

#526 Fix bug in `broadcast_shape_iter` when all dims are broadcastable
  aesara/tensor/extra_ops.py
  tests/tensor/test_extra_ops.py
Labels: bug, important

#510 Replace `scan_args` with `ScanArgs`
  aesara/link/jax/dispatch.py
  aesara/scan/opt.py
  aesara/scan/utils.py
  doc/extending/scan.rst
  tests/scan/test_utils.py
Labels: enhancement
