Repository aesara-devs/aesara, pull requests merged in 2021-11, with the labels that each got.

#647 Add shape assertion to `local_useless_alloc`
  aesara/tensor/basic_opt.py
  tests/tensor/test_basic_opt.py
Labels: bug, optimizations

#652 Update the developer start guide
  .github/PULL_REQUEST_TEMPLATE.md
  aesara/misc/doubleop.py
  doc/dev_start_guide.rst
  doc/extending/extending_aesara.rst
  doc/extending/scan.rst
Labels: documentation, enhancement

#653 Remove introductory sentences from `dev_start_guide.rst`
  doc/dev_start_guide.rst
Labels: documentation, enhancement

#663 fixed typo on tutorial --extending aesara
  doc/extending/extending_aesara.rst
Labels: bug, documentation

#655 Make input mismatch TypeError in make_node more readable
  aesara/graph/op.py
  tests/graph/test_op.py
Labels: enhancement, refactor

#667 Made the RandomState conversion of Numba a valid RandomStateType
  aesara/link/numba/dispatch/basic.py
  aesara/link/numba/dispatch/random.py
  tests/link/test_numba.py
Labels: bug, important, numba

#678 Make `ScalarConstant` a subclass of `ScalarVariable`
  aesara/scalar/basic.py
Labels: refactor

#680 Do not add `SpecifyShape` to constant sizes in `RandomVariable`
  aesara/tensor/random/utils.py
  tests/tensor/random/test_opt.py
Labels: enhancement

#650 Remove `TensorConstant.tag.unique_value`
  aesara/scan/opt.py
  aesara/tensor/basic.py
  aesara/tensor/math_opt.py
  aesara/tensor/var.py
Labels: refactor
