Repository aesara-devs/aesara, pull requests merged in 2021-08, with the labels that each got.

#548 Fix scope issue in `UltraFastScalarSigmoid.c_code`
  aesara/tensor/nnet/sigm.py
  tests/tensor/nnet/test_sigm.py
Labels: bug, important

#504 Add `cho_solve` `Op`
  aesara/tensor/slinalg.py
  tests/tensor/test_slinalg.py
Labels: enhancement, new operator

#556 Make `TensorConstant` a subclass of `TensorVariable`
  aesara/tensor/var.py
Labels: enhancement, refactor

#560 Implement `DeepCopyOp.infer_shape`
  aesara/compile/ops.py
Labels: enhancement

#566 Fix a bug in an aesara.scan warning message
  aesara/scan/basic.py
Labels: bug

#555 Cast output of `local_func_inv` and `local_exp_log` rewrites
  aesara/tensor/math_opt.py
  tests/tensor/test_math_opt.py
Labels: enhancement, optimizations

#550 Preserve inplace operators in local_ultra_fast_sigmoid
  aesara/tensor/nnet/sigm.py
  tests/tensor/nnet/test_sigm.py
Labels: enhancement, optimizations

#577 Fix in-place updates performed on scalars in Numba
  aesara/link/numba/dispatch.py
  tests/link/test_numba.py
Labels: bug, important, numba
