Repository aesara-devs/aesara, pull requests merged in 2021-06, with the labels that each got.

#445 Rename scalar/basic_scipy to scalar/math
  aesara/gpuarray/elemwise.py
  aesara/gpuarray/opt.py
  aesara/link/numba/dispatch.py
  aesara/scalar/__init__.py
  aesara/scalar/math.py
  tests/link/test_numba.py
  tests/scalar/test_math.py
  tests/tensor/test_math_opt.py
Labels: refactor

#462 Change references to `master` branch to `main`
  .github/workflows/pypi.yml
  .github/workflows/test.yml
  Makefile
  README.rst
  doc/dev_start_guide.rst
  doc/extending/jax_op.rst
Labels: important

#468 Update `pymc-devs` references to `aesara-devs`
  CONTRIBUTING.md
  README.rst
  aesara/compile/profiling.py
  aesara/configparser.py
  aesara/ifelse.py
  aesara/misc/pkl_utils.py
  aesara/raise_op.py
  aesara/scan/__init__.py
  aesara/scan/basic.py
  aesara/scan/op.py
  aesara/scan/opt.py
  aesara/scan/scan_perform.pyx
  aesara/scan/utils.py
  conda/meta.yaml
  doc/.static/version_switch.js
  doc/LICENSE.txt
  doc/acknowledgement.rst
  doc/conf.py
  doc/dev_start_guide.rst
  doc/extending/jax_op.rst
  doc/index.rst
  doc/install_generic.inc
  doc/introduction.rst
  doc/library/tensor/basic_opt.rst
  doc/library/tensor/math_opt.rst
  doc/library/tensor/random/basic.rst
  doc/library/tensor/random/index.rst
  doc/updating.rst
  setup.py
  tests/record.py
  tests/test_determinism.py
  tests/test_ifelse.py
Labels: important

#471 Call axis reducer functions directly in `create_multiaxis_reducer`
  aesara/link/numba/dispatch.py
Labels: important, numba

#479 Set Actions workflows `concurrency` to `cancel-in-progress`
  .github/workflows/pypi.yml
  .github/workflows/test.yml
Labels: ci, enhancement

#481 Add the new logo
  README.rst
  doc/images/aesara_logo_2400.png
Labels: documentation

#483 Rename `abs_` to `abs`
  aesara/compile/nanguardmode.py
  aesara/scalar/basic.py
  aesara/tensor/extra_ops.py
  aesara/tensor/inplace.py
  aesara/tensor/math.py
  aesara/tensor/math_opt.py
  aesara/tensor/var.py
  doc/library/tensor/basic.rst
  tests/tensor/test_inplace.py
  tests/tensor/test_math.py
  tests/tensor/test_math_opt.py
Labels: enhancement, numpy compatibility

#484 Restrict Actions workflow concurrency group to pull requests
  .github/workflows/pypi.yml
  .github/workflows/test.yml
Labels: ci

#490 Add `logsumexp` and `logaddexp`
  aesara/tensor/math.py
  tests/tensor/test_math.py
Labels: enhancement

#403 Added Numba RV conversion
  aesara/link/numba/dispatch.py
  aesara/link/numba/linker.py
  tests/link/test_numba.py
Labels: important, numba

#502 Simplify Numba reducer functions
  aesara/link/numba/dispatch.py
Labels: enhancement, numba
