Repository aesara-devs/aesara, pull requests merged in 2021-05, with the labels that each got.

#391 Implement Numba conversion for `CAReduce` `Op`s
  aesara/link/numba/dispatch.py
  tests/link/test_numba.py
Labels: important, numba

#396 Add missing f-string in configparser exception
  aesara/configparser.py
Labels: bug

#394 Add a generic Numba conversion function for `Op.perform` implementations
  aesara/link/numba/dispatch.py
  tests/link/test_numba.py
Labels: important, numba

#413 Simplify `Reshape`'s`tuple` creation during Numba conversion
  aesara/link/numba/dispatch.py
  tests/link/test_numba.py
Labels: enhancement, numba

#419 Fix `AttributeError` in Cython version of `Scan`'s exception handling
  aesara/scan/c_code/scan_perform.c
  aesara/scan/scan_perform.pyx
  aesara/scan/scan_perform_ext.py
  tests/scan/test_basic.py
Labels: bug

#422 Revert `FunctionGraph` `Variable` replacement warning
  aesara/graph/fg.py
Labels: enhancement

#443 Lift broadcast-only `DimShuffle`s through `RandomVariable` `Op`s
  aesara/tensor/random/opt.py
  tests/tensor/random/test_opt.py
Labels: enhancement, optimizations

#447 Fix `ifelse` `str` representation
  aesara/ifelse.py
  tests/test_ifelse.py
Labels: bug

#448 Do not require `fgraph.clients` entries in `RandomVariable` rewrites
  aesara/tensor/random/opt.py
Labels: enhancement, optimizations

#452 Include `__props__` in `RandomVariable.__str__`
  aesara/tensor/random/op.py
  tests/tensor/random/test_op.py
Labels: enhancement
