Repository aesara-devs/aesara, pull requests merged in 2021-12, with the labels that each got.

#693 Fix a `RandomVariable` `DimShuffle` lift case for empty sizes
  aesara/tensor/random/opt.py
  tests/tensor/random/test_opt.py
Labels: bug, optimizations

#698 Update the articles for extending `Type`s
  doc/extending/ctype.rst
  doc/extending/type.rst
  doc/tutorial/index.rst
Labels: documentation, enhancement, refactor

#656 Adding support for nightly builds
  .github/workflows/nightly.yml
  setup.py
Labels: enhancement, ci

#676 Split `solve_triangular` functionality from the `Solve` class into separate `SolveTriangular` class
  aesara/tensor/slinalg.py
  tests/link/test_numba.py
  tests/tensor/test_slinalg.py
Labels: refactor, scipy compatibility
