Repository aesara-devs/aesara, pull requests merged in 2022-06, with the labels that each got.

#975 Allow newlines in `__str__` output printed by `fgraph_to_python`
  aesara/link/utils.py
  tests/link/test_utils.py
Labels: bug, JAX, Numba

#970 Added "What is Aesara" section to documentation
  README.rst
Labels: documentation

#976 Clone inner-graph before compiling in `OpFromGraph`
  aesara/compile/builders.py
  tests/compile/test_builders.py
Labels: bug, important

#986 Broadcast matrix inputs to Gemm
  aesara/tensor/blas.py
  tests/tensor/test_blas.py
Labels: bug, request discussion, performance concern

#995 Add optional `strict` argument to `Type.is_valid_value`
  aesara/graph/type.py
  aesara/tensor/random/type.py
  tests/tensor/random/test_type.py
Labels: bug, important, random sampling, typing

#994 Jax implementation of `log1mexp`
  aesara/link/jax/dispatch.py
  tests/link/test_jax.py
Labels: enhancement, JAX
