Repository aesara-devs/aesara, pull requests merged in 2022-01, with the labels that each got.

#719 Make `TensorConstant`s print their names when specified
  aesara/tensor/var.py
  tests/tensor/test_var.py
Labels: enhancement

#721 Updated versioneer to enable Python 3.11 and removed some Python 2 and 3.6 support.
  Makefile
  aesara/_version.py
  aesara/tensor/blas_c.py
  aesara/tensor/nnet/basic.py
  aesara/tensor/var.py
  doc/requirements.inc
  doc/tutorial/debug_faq.rst
  doc/tutorial/examples.rst
  requirements.txt
  setup.py
  versioneer.py
Labels: enhancement, important

#713 Tests for input checks in tensor/signal/pool.py
  tests/tensor/signal/test_pool.py
Labels: enhancement, testing

#725 Fix limit of `log1mexp` gradient at zero and improve numerical stablity
  aesara/scalar/math.py
  tests/tensor/test_math.py
Labels: bug, enhancement

#734 Change FunctionGraph.change_input to change_node_input
  aesara/compile/function/types.py
  aesara/graph/features.py
  aesara/graph/fg.py
  tests/graph/test_fg.py
Labels: graph rewriting, refactor

#735 Remove optimize_graph_with_cache, it's not used
  aesara/compile/function/types.py
  aesara/configdefaults.py
  tests/compile/function/test_types.py
Labels: refactor

#743 Introduce `aesara.as_symbolic`
  aesara/__init__.py
  aesara/graph/opt.py
  aesara/tensor/__init__.py
  aesara/tensor/type_other.py
  tests/tensor/test_type_other.py
Labels: enhancement

#763 Reintroduce deprecated `broadcastable` keyword arguments
  aesara/tensor/sharedvar.py
  aesara/tensor/type.py
  tests/tensor/test_sharedvar.py
  tests/tensor/test_type.py
Labels: important

#762 Fix bad Windows free in `dimshuffle.c`
  aesara/tensor/c_code/dimshuffle.c
Labels: bug, important, Windows

#769 Add a Numba implementation for the `BroadcastTo` `Op`
  aesara/link/numba/dispatch/extra_ops.py
  tests/link/test_numba.py
Labels: enhancement, Numba

#741 Support `n_steps=0` (and empty sequence) case for `Scan`
  aesara/scan/basic.py
  aesara/scan/c_code/scan_perform.c
  aesara/scan/op.py
  aesara/scan/scan_perform.pyx
  aesara/scan/scan_perform_ext.py
  tests/scan/test_basic.py
Labels: bug, Scan

#783 Update the high-level API documentation
  doc/library/index.rst
Labels: documentation

#787 Fixed behaviour of at.subtensor.take when axis is None
  aesara/tensor/subtensor.py
  tests/tensor/test_subtensor.py
Labels: bug

#795 Implement `tril_indices`, `triu_indices`, `triu_indices_from` and `tril_indices_from`
  aesara/tensor/basic.py
  tests/tensor/test_basic.py
Labels: enhancement, NumPy compatibility

#789 Add NumPy RNG constructor `Op`s
  aesara/tensor/random/__init__.py
  aesara/tensor/random/op.py
  tests/tensor/random/test_op.py
Labels: enhancement, important, new operator, RNG-related, NumPy compatibility
