Repository aesara-devs/aesara, pull requests merged in 2022-08, with the labels that each got.

#1095 Refactor and fix static shape issues in `IfElse`
  aesara/ifelse.py
  tests/test_ifelse.py
Labels: bug, important, shape inference, Op implementation

#1100 Fix incorrect setuptools minimum version number
  setup.py
Labels: bug

#1099 Add docstrings for dirichlet, geometric and hypergeometric distributions
  aesara/tensor/random/basic.py
  doc/library/tensor/random/basic.rst
Labels: documentation, random variables

#1088 Allow `size` to broadcast `CategoricalRV` `p` argument
  aesara/link/numba/dispatch/random.py
  aesara/tensor/random/basic.py
  tests/link/test_numba.py
  tests/tensor/random/test_basic.py
Labels: bug, random variables, Op implementation

#1083 Add Owens-T Function `Op`
  aesara/scalar/math.py
  aesara/tensor/inplace.py
  aesara/tensor/math.py
  tests/tensor/test_math_scipy.py
Labels: enhancement, SciPy compatibility, Op implementation

#1111 Allow JAX Reshape to work with constant shape inputs
  aesara/link/jax/dispatch.py
  tests/link/test_jax.py
Labels: JAX

#1112 Remove unnecessary code in `local_useless_AdvancedSubtensor1` and refactor tests
  aesara/tensor/subtensor_opt.py
  tests/tensor/test_subtensor_opt.py
Labels: testing, graph rewriting, refactor

#1124 Add a C implementation for `TensorFromScalar`
  aesara/tensor/basic.py
Labels: enhancement, C-backend, Op implementation

#1132 Add pip as an explicit docs dependency
  doc/environment.yml
Labels: bug

#1131 Revert to lazy loaded `aesara.link.c.cutils`
  aesara/link/c/basic.py
Labels: bug, important

#1133 Fix handling of `numpy.dtype` input in `TensorType`
  aesara/tensor/type.py
  tests/tensor/test_type.py
Labels: bug, important

#1139 Split `aesara.tensor.rewriting.basic` rewrites by their `aesara.tensor` modules
  aesara/compile/builders.py
  aesara/scan/rewriting.py
  aesara/tensor/basic.py
  aesara/tensor/basic_opt.py
  aesara/tensor/blas.py
  aesara/tensor/rewriting/__init__.py
  aesara/tensor/rewriting/basic.py
  aesara/tensor/rewriting/elemwise.py
  aesara/tensor/rewriting/extra_ops.py
  aesara/tensor/rewriting/math.py
  aesara/tensor/rewriting/shape.py
  aesara/tensor/utils.py
  tests/compile/test_builders.py
  tests/tensor/random/test_basic.py
  tests/tensor/rewriting/test_basic.py
  tests/tensor/rewriting/test_elemwise.py
  tests/tensor/rewriting/test_extra_ops.py
  tests/tensor/rewriting/test_math.py
  tests/tensor/rewriting/test_shape.py
  tests/tensor/test_elemwise.py
  tests/tensor/test_shape.py
Labels: enhancement, graph rewriting, refactor

#1144 Move `tensor_copy` rewrite to `aesara.tensor.rewriting.basic`
  aesara/tensor/rewriting/basic.py
  aesara/tensor/rewriting/shape.py
Labels: bug, refactor

#1143 Support duplicate indices in `AdvancedIncSubtensor1`'s Numba implementation
  aesara/link/numba/dispatch/basic.py
  tests/link/test_numba.py
Labels: bug, Numba

#1130 Add a C implementation for `BroadcastTo`
  aesara/tensor/extra_ops.py
  tests/tensor/test_extra_ops.py
Labels: enhancement, C-backend, performance concern, Op implementation

#1154 Add tensor conversion to Numpy-like helper functions
  aesara/tensor/basic.py
  tests/tensor/test_basic.py
Labels: enhancement, NumPy compatibility
