Repository aesara-devs/aesara, pull requests merged in 2022-03, with the labels that each got.

#847 Revert "Pin `jaxlib` to a version less than or equal to 0.1.75"
  .github/workflows/test.yml
  requirements.txt
Labels: JAX

#854 Fix a memory leak in the C implementation of `DimShuffle`
  aesara/tensor/c_code/dimshuffle.c
  tests/tensor/test_elemwise.py
Labels: bug, important, C-backend, performance concern

#759 Add rewrites to remove unnecessary `expm1` operations
  aesara/tensor/math_opt.py
  tests/tensor/test_math_opt.py
Labels: enhancement, graph rewriting

#864 Use new JAX index update approach when available
  aesara/link/jax/dispatch.py
Labels: JAX, important

#865 Fix Numba CAReduce infinite identity values for non-floats
  aesara/link/numba/dispatch/elemwise.py
  tests/link/test_numba.py
Labels: bug, Numba

#867 Use `params` argument in Numba's default `Op.perform` implementation
  aesara/link/numba/dispatch/basic.py
  tests/link/test_numba.py
Labels: bug, important, Numba

#779 Added `Op`s for `np.linspace`, `np.logspace`, and `np.geomspace`
  aesara/tensor/__init__.py
  aesara/tensor/extra_ops.py
  tests/tensor/test_extra_ops.py
Labels: enhancement, new operator, NumPy compatibility

#872 Use type name in `Elemwise` and `CAReduce` `__str__` implementations
  aesara/tensor/elemwise.py
  aesara/tensor/math_opt.py
  tests/tensor/test_elemwise.py
Labels: enhancement, refactor
