Repository aesara-devs/aesara, pull requests merged in 2022-05, with the labels that each got.

#928 Allow broadcasting in `Elemwise.c_code`
  aesara/scalar/basic.py
  aesara/tensor/elemwise.py
  aesara/tensor/elemwise_cgen.py
  tests/tensor/test_elemwise.py
Labels: enhancement, important, C-backend, NumPy compatibility

#947 Patch ldflags and libs in GCC_compile under windows
  aesara/link/c/cmodule.py
  tests/link/c/test_cmodule.py
Labels: bug, Windows, performance concern

#962 Fix the type of `t_fn` in `scan_perform.pyx`
  aesara/scan/c_code/scan_perform.c
  aesara/scan/scan_perform.pyx
  aesara/scan/scan_perform_ext.py
Labels: bug, Scan

#968 Add missing properties to copied `Function` objects
  aesara/compile/function/types.py
  tests/compile/function/test_types.py
Labels: bug

#969 Increase lock scope in `ModuleCache.refresh`
  aesara/link/c/cmodule.py
  tests/link/c/test_cmodule.py
Labels: bug, C-backend
