Repository aesara-devs/aesara, pull requests merged in 2022-09, with the labels that each got.

#1183 Update `options.package_data` section
  setup.cfg
Labels: bug, important

#1181 Update `CheckAndRaise` to handle `ScalarType` inputs
  aesara/raise_op.py
  aesara/scalar/basic.py
  tests/scalar/test_basic.py
  tests/test_raise_op.py
Labels: C-backend, performance concern

#1190 Allow `TensorType.convert_variable` to work with mixed static shapes
  aesara/tensor/type.py
  tests/tensor/test_type.py
Labels: refactor, graph objects

#1199 Fix type inference in Elemwise when inputs have 0 shape
  aesara/tensor/elemwise.py
  tests/tensor/test_elemwise.py
Labels: bug, shape inference

#1201 Fix split output type
  aesara/tensor/basic.py
  tests/tensor/test_basic.py
Labels: bug, important, shape inference

#1186 Implement moveaxis helper
  aesara/tensor/basic.py
  tests/tensor/test_basic.py
Labels: NumPy compatibility

#1187 Add deprecation warning for `rng_mrg`
  aesara/sandbox/rng_mrg.py
Labels: refactor

#1208 Update `pre-commit` hooks
  .pre-commit-config.yaml
Labels: bug, testing, CI

#1209 Make `isort` ignore Cython files
  setup.cfg
Labels: bug, testing, CI

#1189 Update Scan Gibbs sampling example
  doc/library/scan.rst
Labels: documentation

#1210 Pin style CI job to Python 3.9
  .github/workflows/test.yml
Labels: bug, testing, CI

#1218 Stop renaming variables in `Scan`'s merge rewrite
  aesara/scan/rewriting.py
Labels: graph rewriting, Scan, unexpected behavior

#1214 Allow shared RandomState/Generator updates in JAX backend
  aesara/link/jax/linker.py
  tests/link/jax/test_random.py
Labels: JAX, backend compatibility, random variables

#1224 Fix `_debugprint`'s handling of empty profile data
  aesara/printing.py
  tests/test_printing.py
Labels: bug, tooling
