Repository aesara-devs/aesara, pull requests merged in 2022-02, with the labels that each got.

#803 Do not allow `PatternSub` to replace nodes with different number of outputs
  aesara/graph/opt.py
  tests/graph/test_opt.py
  tests/graph/utils.py
Labels: bug, graph rewriting

#446 Require independent dimensions in `size` arguments to multivariate `RandomVariable`s
  aesara/tensor/random/basic.py
  aesara/tensor/random/op.py
  aesara/tensor/random/opt.py
  tests/tensor/random/test_basic.py
  tests/tensor/random/test_opt.py
Labels: refactor, RNG-related

#806 Add JAX conversion for CheckAndRaiseOp
  aesara/link/jax/dispatch.py
  tests/link/test_jax.py
Labels: JAX

#813 Add type hints for default_shape_from_params
  aesara/tensor/random/op.py
Labels: documentation, enhancement

#817 Implement `_get_vector_length` for `Alloc`
  aesara/tensor/basic.py
  tests/tensor/test_basic.py
Labels: enhancement

#822 Use `_props_dict` instead of `_props` in `random_make_inplace`
  aesara/tensor/random/opt.py
  tests/tensor/random/test_opt.py
Labels: refactor, RNG-related

#828 Pin `jaxlib` to a version less than or equal to 0.1.75
  .github/workflows/test.yml
  requirements.txt
Labels: bug, JAX, important

#826 Rename `*shape_from_params` to `*supp_shape_from_params` for clarity
  aesara/tensor/random/basic.py
  aesara/tensor/random/op.py
  tests/tensor/random/test_basic.py
  tests/tensor/random/test_op.py
Labels: refactor

#833 Simplify `RandomVariable._infer_shape`
  aesara/tensor/random/op.py
Labels: enhancement, refactor, RNG-related
