Repository aesara-devs/aesara, pull requests merged in 2022-10, with the labels that each got.

#1234 Make `fgraph_to_python` process `Constant` `FunctionGraph` outputs correctly
  aesara/link/utils.py
  tests/link/test_utils.py
Labels: bug, JAX, important, Numba

#1160 Add gufunc signature to `RandomVariable`'s docstrings
  aesara/tensor/random/basic.py
  doc/library/tensor/random/basic.rst
Labels: documentation, random variables

#1266 Mention common cases in issue template
  .github/ISSUE_TEMPLATE.md
Labels: enhancement

#1269 Fix `SharedVariable.value` usage in `broadcast_shape_iter`
  aesara/tensor/extra_ops.py
  tests/tensor/test_extra_ops.py
Labels: bug

#1265 Add documentation for `aesara.as_symbolic()`
  doc/library/index.rst
Labels: documentation

#827 Add type hint to `RandomVariable.rng_fn`
  aesara/tensor/random/op.py
Labels: typing

#1278 Update flake8 repo and version in `pre-commit` config
  .pre-commit-config.yaml
Labels: testing, tooling
