Repository aesara-devs/aesara, pull requests merged in 2022-11, with the labels that each got.

#1211 Add Student's t `RandomVariable`
  aesara/tensor/random/basic.py
  doc/library/tensor/random/basic.rst
  tests/tensor/random/test_basic.py
Labels: random variables

#1283 Add documentation for contributing to Aesara
  CONTRIBUTING.md
  README.rst
Labels: documentation

#1293 Update time.clock() to time.perf_counter() in documentation under tutorial/conditions
  doc/tutorial/conditions.rst
Labels: documentation, refactor

#1298 Make `as_symbolic` work with sparse matrices
  aesara/sparse/basic.py
Labels: enhancement, sparse tensors

#1300 Update codecov-action version
  .github/workflows/test.yml
Labels: bug, CI

#1282 Add `name` argument to `Variable.clone`
  aesara/compile/sharedvalue.py
  aesara/graph/basic.py
  tests/graph/test_basic.py
Labels: enhancement

#1306 Remove redundant `graph_inputs` usage in `OpFromGraph`
  aesara/compile/builders.py
  aesara/scan/op.py
  tests/scan/test_basic.py
Labels: enhancement, refactor, performance concern

#1302 Remove `CholeskyGrad` Op
  aesara/tensor/slinalg.py
  tests/tensor/test_slinalg.py
Labels: refactor

#1020 Add `Op`s for `solve_discrete_lyapunov` and `solve_continuous_lyapunov`
  aesara/tensor/slinalg.py
  tests/tensor/test_slinalg.py
Labels: SciPy compatibility, tensor algebra, Op implementation

#884 Harmonize softplus implementations
  aesara/link/jax/dispatch/scalar.py
  aesara/scalar/math.py
Labels: enhancement, refactor

#1312 Replace time.time with time.perf_counter
  aesara/compile/profiling.py
  aesara/gradient.py
  aesara/graph/features.py
  aesara/graph/fg.py
  aesara/graph/rewriting/basic.py
  aesara/link/c/cmodule.py
  aesara/link/vm.py
  aesara/misc/check_blas.py
  aesara/misc/elemwise_time_test.py
  aesara/misc/latence_gpu_transfert.py
  aesara/scan/op.py
  aesara/tensor/blas.py
  aesara/tensor/rewriting/elemwise.py
  tests/link/test_vm.py
  tests/sandbox/test_rng_mrg.py
  tests/sparse/sandbox/test_sp.py
  tests/sparse/test_basic.py
  tests/tensor/nnet/speed_test_conv.py
  tests/tensor/nnet/test_conv.py
  tests/tensor/nnet/test_conv3d2d.py
  tests/tensor/rewriting/test_math.py
  tests/tensor/test_gc.py
Labels: enhancement, refactor, tooling

#960 Add ARM dev environment dependencies
  environment-arm.yml
Labels: MacOS, Conda

#1313 Type hint of `specify_shape` does not allow for None in shape
  aesara/tensor/shape.py
Labels: typing
