Repository aesara-devs/aesara, pull requests merged in 2022-04, with the labels that each got.

#883 Add JAX implementation for `BroadcastTo`
  aesara/link/jax/dispatch.py
  tests/link/test_jax.py
Labels: enhancement, JAX

#892 Fix `Scan.truncate_gradient` default value and type
  aesara/scan/op.py
Labels: bug, Scan

#899 Do not use CheckAndRaise c_code for non-dense inputs
  aesara/raise_op.py
  tests/test_raise_op.py
Labels: bug, sparse tensors

#903 Remove unnecessary cloning from `Scan` rewrites
  aesara/scan/opt.py
Labels: enhancement, graph rewriting, Scan

#905 Fix shared variable comparisons in `OpFromGraph.make_node`
  aesara/compile/builders.py
  tests/compile/test_builders.py
Labels: bug

#799 Enabled type checking as described by PEP 561
  aesara/py.typed
  setup.py
Labels: enhancement, typing

#906 Add a missing inputs check to `OpFromGraph`
  aesara/compile/builders.py
  tests/compile/test_builders.py
Labels: enhancement

#907 Allow shared variable input chnages in `OpFromGraph.make_node`
  aesara/compile/builders.py
  tests/compile/test_builders.py
  tests/scan/test_opt.py
Labels: bug, enhancement, important, Scan

#908 Make SciPy-based `RandomVariable` return values writeable
  aesara/tensor/random/basic.py
  tests/tensor/random/test_basic.py
Labels: bug, important, RNG-related, SciPy compatibility

#911 Update the Cython `Scan` implementation's version number
  aesara/scan/c_code/scan_perform.c
  aesara/scan/scan_perform.pyx
  aesara/scan/scan_perform_ext.py
Labels: bug, important, Scan

#914 Fix error with scalar inputs in CAReduce and squeeze
  aesara/tensor/elemwise.py
  aesara/tensor/extra_ops.py
  tests/tensor/test_elemwise.py
  tests/tensor/test_extra_ops.py
Labels: bug

#920 Add `kwargs` to `OpFromGraph`s constructed in `OpFromGraph.make_node`
  aesara/compile/builders.py
  tests/compile/test_builders.py
Labels: bug

#926 Fix `ScipyRandomVariable` issue when `size` is `None` and parameters are all broadcastable
  aesara/tensor/random/basic.py
  tests/tensor/random/test_basic.py
Labels: bug, important, random sampling, SciPy compatibility

#932 Add code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#760 Add rewrite to merge consecutive `Join`ed `Subtensor`s
  aesara/tensor/subtensor_opt.py
  tests/tensor/test_subtensor_opt.py
Labels: enhancement, graph rewriting

#941 Fix static shape inference in `DimShuffle`
  aesara/tensor/elemwise.py
  tests/tensor/test_elemwise.py
Labels: bug, important
