Repository aesara-devs/aesara, pull requests merged in 2023-04, with the labels that each got.

#1487 Enable `pip` caching in CI
  .github/workflows/dev-builds.yml
  .github/workflows/pypi.yml
  .github/workflows/test.yml
  .github/workflows/update-pre-commit.yml
Labels: enhancement, CI

#1493 Removes pydot2 dependency
  requirements-rtd.txt
Labels: bug, setup and installation

#1494 Remove type ignore in `aesara.link.c.exceptions`
  aesara/link/c/exceptions.py
Labels: typing

#1485 Implement ConvolveOp
  aesara/tensor/basic.py
  aesara/tensor/math.py
  tests/tensor/test_math.py
Labels: enhancement, NumPy compatibility, Op implementation
