Repository aesara-devs/aesara, pull requests merged in 2023-01, with the labels that each got.

#1381 Update copyright years
  doc/LICENSE.txt
  doc/conf.py
Labels: documentation

#1383 Give a CI error message when lazylinker_c.c missing
  .github/workflows/pypi.yml
Labels: enhancement, CI

#1386 Enable dependabot to update github-actions
  .github/dependabot.yml
Labels: CI

#1378 Add GHA workflow to autoupdate pre-commit hooks
  .github/workflows/update-pre-commit.yml
Labels: enhancement, CI

#1382 Move aesara-cache into aesara.bin package
  aesara/bin/__init__.py
  aesara/bin/aesara_cache.py
  bin/__init__.py
  bin/aesara-cache
  bin/aesara_cache.py
  pyproject.toml
Labels: enhancement, refactor

#1398 Fix for recent failures in setup-miniconda
  .github/workflows/test.yml
Labels: CI, setup and installation

#1288 Add Gaussian Hypergeometric Function `Hyp2F1`
  aesara/scalar/math.py
  aesara/tensor/inplace.py
  aesara/tensor/math.py
  aesara/tensor/special.py
  tests/tensor/test_math_scipy.py
  tests/tensor/test_special.py
Labels: SciPy compatibility, Op implementation

#1384 Migrate from setuptools to hatchling
  .github/workflows/pypi.yml
  .gitignore
  MANIFEST.in
  pyproject.toml
Labels: enhancement

#1399 Add numerical stabilization for difference of exponentials
  aesara/tensor/rewriting/math.py
  tests/tensor/test_math.py
Labels: enhancement, graph rewriting
