Repository aesara-devs/aesara, pull requests merged in 2023-02, with the labels that each got.

#1405 Ensure git archives contains version info
  .git_archival.txt
  .gitattributes
Labels: enhancement, dependencies, setup and installation

#1412 Add `SharedVariable.default_update` graphs to `debugprint`
  aesara/printing.py
  tests/graph/utils.py
  tests/test_printing.py
Labels: enhancement, tooling

#1411 Update the README
  README.md
  README.rst
Labels: documentation

#1416 Add documentation tagline to the README
  README.md
Labels: documentation

#1417 Fix link to the mission statement in the README
  README.md
Labels: bug, documentation

#972 Fix C++11 narrowing error on Mac OS
  aesara/link/c/cmodule.py
  tests/link/c/test_cmodule.py
Labels: bug, C-backend, MacOS

#1442 Update Actions versions in `update-pre-commit.yml`
  .github/workflows/update-pre-commit.yml
Labels: CI

#1452 Skip test_cache_race_condition on macOS
  tests/link/c/test_cmodule.py
Labels: testing, MacOS

#1454 Add tests and doc to sdist
  pyproject.toml
Labels: setup and installation
